// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var BetterSqlite3 = require("better-sqlite3");

var Statement = /* module */[];

var Config = /* module */[];

function make(path, memory, readonly, fileMustExist, _) {
  var tmp = { };
  if (memory) {
    tmp.memory = memory[0];
  }
  if (readonly) {
    tmp.readonly = readonly[0];
  }
  if (fileMustExist) {
    tmp.fileMustExist = fileMustExist[0];
  }
  return new BetterSqlite3(path, tmp);
}

var Connection = /* module */[
  /* Config */Config,
  /* make */make
];

exports.Statement = Statement;
exports.Connection = Connection;
/* better-sqlite3 Not a pure module */
